default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: diaper_dev
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  timeout: 5000

test:
  <<: *default
  database: diaper_test
  timeout: 5000

staging:
  <<: *default
  # This is really staging! However, we inherit the
  # same configurations as production because staging
  # use to run through environments/production.rb configuration
  #
  # TODO - update database name in staging
  database: diaper_production
  password: <%= ENV['DIAPER_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: diaper_production
  password: <%= ENV['DIAPER_DATABASE_PASSWORD'] %>
